# Generated by Django 4.1.7 on 2023-05-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZOO_App', '0004_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilhete',
            name='intervalo_idade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bilhete',
            name='preco',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='donativo',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='donativo',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='preco_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
    ]
