# Generated by Django 4.1.7 on 2023-05-11 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZOO_App', '0005_alter_bilhete_intervalo_idade_alter_bilhete_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtocarinhocompras',
            name='produtocarinhocompras_pk',
        ),
        migrations.RemoveField(
            model_name='utilizadornoticia',
            name='utilizadornoticia_pk',
        ),
        migrations.AddField(
            model_name='faturaproduto_pk',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produtocarinhocompras_pk',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='utilizadornoticia_pk',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='FaturaProduto',
        ),
        migrations.DeleteModel(
            name='ProdutoCarinhoCompras',
        ),
        migrations.DeleteModel(
            name='utilizadorNoticia',
        ),
    ]
