# Generated by Django 4.1.7 on 2023-05-12 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZOO_App', '0006_remove_produtocarinhocompras_produtocarinhocompras_pk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilizadorComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('comentario', models.CharField(max_length=200)),
                ('utilizador_noticia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ZOO_App.utilizadornoticia_pk')),
            ],
        ),
    ]
