# Generated by Django 4.1.7 on 2023-05-12 14:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZOO_App', '0007_utilizadorcomentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('comentario', models.CharField(max_length=200)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ZOO_App.noticia')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ZOO_App.utilizador')),
            ],
        ),
        migrations.RemoveField(
            model_name='bilheteutilizador',
            name='data_bilhete',
        ),
        migrations.AddField(
            model_name='utilizadornoticia_pk',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UtilizadorComentario',
        ),
    ]
