# Generated by Django 4.1.7 on 2023-05-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZOO_App', '0008_comentario_remove_bilheteutilizador_data_bilhete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZOO_App.noticia'),
        ),
        migrations.AlterField(
            model_name='noticiatag_pk',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZOO_App.noticia'),
        ),
        migrations.AlterField(
            model_name='utilizadornoticia_pk',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZOO_App.noticia'),
        ),
    ]
